### ISSUE TITLE
Update SystemAgentDelegate to send additional error code.

### ISSUE THREAD

**Issue by Minddol** [nugu-developers/nugu-ios#105]
# Overviews
Application need to play local TTS when error codes are received.
## Category

- [ ] New feature 
- [x] Update feature
- [ ] Update documentation
- [ ] Idea
- [ ] Architecture

## Reference  
[Requirements and resources(Private)](https://tde.sktelecom.com/wiki/pages/viewpage.action?pageId=253424596)
[Summary(Private)](https://tde.sktelecom.com/wiki/pages/viewpage.action?pageId=258313631)

**Comment by yHoonyK** [comment]
@jin-marino, Adopt `SystemAgentDelegate` in sample application.

**Comment by jin-marino** [comment]
> @jin-marino, Adopt `SystemAgentDelegate` in sample application.

Adoption complete!
