### ISSUE TITLE
Update 'NUGU SDK Guide' Wiki

### ISSUE THREAD

**Issue by yHoonyK** [nugu-developers/nugu-ios#129]
# Overviews

## Category

- [ ] New feature 
- [ ] Update feature
- [x] Update documentation
- [ ] Idea
- [ ] Architecture

## Summary
Nugu developers documentation 에서 모든 가이드를 제공하는 방향으로 진행중입니다.
## Reference  
https://github.com/nugu-developers/nugu-ios/wiki/How-to-use-NUGU-SDK-for-iOS

**Comment by yHoonyK** [comment]
@Minddol, Please write the `SpeakerAgent`

**Comment by yHoonyK** [comment]
`SpeakerAgent` is not fix spec now.
It will be update after fix `SpeakerAgent`.

**Comment by Minddol** [comment]
NUGU Developers documentation 고도화 이후 wiki 에서 제공할 contents 는 재검토 되어야 합니다.
