### ISSUE TITLE
Make light weight container for components

### ISSUE THREAD

**Issue by childc** [nugu-developers/nugu-ios#182]
# Overviews
`NuguClient` holds all of managers and agents at this time.
But the components can be separated from `NuguClient` and It's life cycle.

## Category

- [x] New feature 
- [ ] Update feature
- [ ] Update documentation
- [ ] Idea
- [ ] Architecture

## Summary
1. Puts all of components into container when `NuguClient` is initiated.
2. Wrap the managers APIs and Make App. not needed to access Managers directly.

## Reference  
`Swinject` project

**Comment by Minddol** [comment]
@childc 님, 이슈 close 하겠습니다.
