### ISSUE TITLE
Voice recognition and Server side end point detection

### ISSUE THREAD

**Issue by childc** [nugu-developers/nugu-ios#236]
# Overviews

## Category

- [x] New feature 
- [ ] Update feature
- [ ] Update documentation
- [ ] Idea
- [ ] Architecture

## Summary
Send wake up pcm data to server to recognize who's voice.

**Comment by Minddol** [comment]
서버 구현이 아직 준비되지 않았습니다.

**Comment by childc** [comment]
If you looking for utopia, You'd better to use `Clova`, `Siri`, `Google` rather than aria.
