### ISSUE TITLE
Consider thread issue of `DisplayAgent`'s contextRequest when sending event

### ISSUE THREAD

**Issue by jin-marino** [nugu-developers/nugu-ios#239]
# Overviews

## Category

- [ ] New feature 
- [ ] Update feature
- [ ] Update documentation
- [ ] Idea
- [ ] Architecture

## Summary
`DisplayAgent`'s contextRequesting method should be called in main thread which can occur crash when sending event. Temporarily, crash has resolved by checking `Thread.current.isMainThread()` method. Better solution should be discussed.

**Comment by Minddol** [comment]
Delegation 함수 내에서 worker thread 작업이 필요할 수도 있고, main thread 에서의 처리 필요성은 application 에서 판단는 것이 자연스럽다는 T 전화측 의견을 수용하여 Agent 에서는 main queue 를 사용하지 않고, delegation 함수 처리 결과를 completion block 으로 전달 받도록 수정하였습니다.
