### ISSUE TITLE
Support multi-platform

### ISSUE THREAD

**Issue by yHoonyK** [nugu-developers/nugu-ios#298]
# Overviews
Support nugu-sdk for watchOS/macOS/tvOS/iOS

## Category
- [x] New feature 
- [ ] Update feature
- [ ] Update documentation
- [ ] Idea
- [ ] Architecture

**Comment by yHoonyK** [comment]
Research `XCFramework`

* Reference
WWDC: https://developer.apple.com/videos/play/wwdc2019/416/
Translated by Korean: http://minsone.github.io/ios/mac/ios-wwdc-2019-binary-frameworks-in-swift-little-summary-and-translate

**Comment by yHoonyK** [comment]
Set `nugu-ios` project for multi-platform.

### Trial list
- [x] Update `supported-platforms` to multi-platform (tvOS, watchOS, iOS, MacOS)
- [ ] Separates the target for each platform.
- [ ] Sample application use only based on cocoapods.

**Comment by childc** [comment]
`SilverTray` supports multi-platform.

**Comment by childc** [comment]
NUGU SDK supports iOS, catalyst, watchOS, macOS, tvOS now.
