### ISSUE TITLE
Reduce delay of starting microphone.

### ISSUE THREAD

**Issue by Minddol** [nugu-developers/nugu-ios#617]
# Overviews

## Category

- [ ] New feature 
- [x] Update feature
- [ ] Update documentation
- [ ] Idea
- [ ] Architecture

## Summary
아래와 같은 이유로 `KeywordDetector` 가 동작에 지연이 발생하고 있음.
- Foreground 진입시 0.5초 delay 후 녹음 시작
- Audio output 사용 완료 후 notifyOthersOnDeactivation 호출시 녹음 재시작

## Reference  
https://tde.sktelecom.com/pms/browse/AIAGENTQA-706
https://tde.sktelecom.com/pms/browse/AIAGENTQA-716

**Comment by childc** [comment]
기획상 요구조건이 iOS의 사용형태와 매우 동떨어져있어 어쩔 수 없습니다.
