### ISSUE TITLE
Though user pressed next button. But Previous song is played one more time.

### ISSUE THREAD

**Issue by childc** [nugu-developers/nugu-ios#647]
## NUGU SDK for iOS Environment
0.26.x

- NUGU SDK for iOS version:
- iOS version: 14.x
- Xcode version: 12.x
- Swift version: 5.x
- Dependency manager:
  - [ ] Cocoapods
  - [x] Carthage
  - [ ] Manually

## What did you do?
User pressed next button during play the music

## What did you expect to happen?
Play next song

## What happened instead?
Played previous song

## Related issue on TDE
https://tde.sktelecom.com/pms/browse/AIAGENTQA-793

## Reference documentation to resolve
https://tde.sktelecom.com/wiki/pages/viewpage.action?pageId=195236634

**Comment by Minddol** [comment]
Fixed bug in `Redis` server.
