### ISSUE TITLE
CarPlay sound quality is reduced when using `KeywordDetector`

### ISSUE THREAD

**Issue by Minddol** [nugu-developers/nugu-ios#709]
## NUGU SDK for iOS Environment

- NUGU SDK for iOS version: 0.28.1

## What did you do?
"이름을 불러 대화하기" 옵션이 설정된 상태에서 CarPlay 연결 후 FLO 앱 실행

## What did you expect to happen?
"이름을 불러 대화하기" 기능이 비활성화 되어 음질 저하 현상이 발생하지 않아야 함

## What happened instead?
`NuguAudioSessionManager.isCarplayConnected()` 가 false 을 반환하여 "이름을 불러 대화하기" 기능이 활성화 되고 음질 저하 현상이 발생 하며 `AVAudioSession.routeChangeNotification` event 가 발생하지 않음.

**Comment by childc** [comment]
No way to resolve this problem.
iPhone supports up to 24khz of sample rate in PlayAndRecode.

You had better use the other asr solution than aria.
