### ISSUE TITLE
Adopt CI/CD

### ISSUE THREAD

**Issue by yHoonyK** [nugu-developers/nugu-ios#71]
# Overviews

## Category
- [ ] New feature 
- [x] Update feature
- [ ] Update documentation
- [x] Idea
- [ ] Architecture
- [x] CI/CD

## Summary
- NUGU SDK for iOS needs CI/CD. 
- CI/CD requirement list
  1. Version update (check cocoapods, carthage)
  2. Static analysis
  3. Run test case (Check code coverage)
  4. Support Swiftlint 
  5. Something else

## Reference  
None

**Comment by Minddol** [comment]
CI/CD requirement 세부 항목 나눠서 issue 생성하겠습니다.
