### ISSUE TITLE
Reduce the delay it takes to start the `ASRAgent`.

### ISSUE THREAD

**Issue by Minddol** [nugu-developers/nugu-ios#727]
# Overviews
Keyword detect <-> DialogState.Listening 사이의 delay 를 최소화 한다.

## Category

- [ ] New feature 
- [x] Update feature
- [ ] Update documentation
- [ ] Idea
- [ ] Architecture

## Reference  
https://tde.sktelecom.com/pms/browse/NUGUPM-4845

**Comment by Minddol** [comment]
os_signpost 로 반복 테스트 결과
MicInputProvider.start	452.59 ms
AudioSessionManager.updateAudioSession 155.75 ms
MicInputProvider.stop	93.51 ms

MicInputProvider.start 가 가장오래 걸림.

**Comment by Minddol** [comment]
MicInputProvider 를 재시작 하지 않도록 처리하면
MicInputProvider.start	113.92 µs
AudioSessionManager.updateAudioSession 905.71 ms
MicInputProvider.stop	179.39 µs

AudioSessionManager.updateAudioSession 가 느려짐(?)

**Comment by Minddol** [comment]
Builder pattern 적용 완료 후 재검토

**Comment by childc** [comment]
어차피 음성인식기의 성능이 매우 떨어지므로, 해당 작업은 의미가 없습니다.
