### ISSUE TITLE
Code-level documentation

### ISSUE THREAD

**Issue by yHoonyK** [nugu-developers/nugu-ios#77]
# Overviews

## Category

- [ ] New feature 
- [ ] Update feature
- [x] Update documentation
- [ ] Idea
- [ ] Architecture

## Summary
Need to write code-level documentation.
- NuguInterface
- NuguClientKit
- NuguCore

## Reference  
None

**Comment by Minddol** [comment]
모듈 통합 후 다시 시작

**Comment by childc** [comment]
This is done since v1.0.0
